from PIL import Image


# Get a range of chars for construction of dicts
# This uses ord, so make sure not to have your range go over
# any unwanted chars.
def char_range(cStart, cEnd):
    for c in range(ord(cStart), ord(cEnd)+1):
        yield chr(c)

# The autogenerated code is generated in a class so that it's easier to 
# collapse in editors/IDEs.

print('# -----START AUTOGENERATED CODE-----')
print('class LetterPrinter:\n\t')

for c in char_range('A', 'Z'):
	im = Image.open('letters/{}.png'.format(c))
	print('\t@staticmethod\n\tdef letter_city_{}():\n\t\treturn ({}, {})\n'.format(c, im.width, im.tobytes() + b'\x00\x00\x00\x00'*im.width*(18-im.height)))	

for c in char_range('a', 'z'):
	im = Image.open('letters/{}.png'.format(c))
	print('\t@staticmethod\n\tdef letter_city_{}():\n\t\treturn ({}, {})\n'.format(c, im.width, im.tobytes() + b'\x00\x00\x00\x00'*im.width*(18-im.height)))

print('\t@staticmethod\n\tdef letter_city_space():\n\t\treturn (5, None)\n')
# print(""im.tobytes())

print('LETTER_ARR_CITY = {')
keyVals = []
for c in char_range('A', 'Z'):
	keyVals.append('\t\'{}\': LetterPrinter.letter_city_{}'.format(c, c))

for c in char_range('a', 'z'):
	keyVals.append('\t\'{}\': LetterPrinter.letter_city_{}'.format(c, c))
keyVals.append('\t\' \': LetterPrinter.letter_city_space')
print(',\n'.join(keyVals))
print('}')
print('# -----END AUTOGENERATED CODE-----')