from PIL import Image


# Get a range of chars for construction of dicts
# This uses ord, so make sure not to have your range go over
# any unwanted chars.
def char_range(cStart, cEnd):
    for c in range(ord(cStart), ord(cEnd)+1):
        yield chr(c)

# The autogenerated code is generated in a class so that it's easier to 
# collapse in editors/IDEs.
landmarkDict = {
	"subfolder": "landmark",
	"height": 13,
	"spaceLength": 4
}

cityDict = {
	"subfolder": "city",
	"height": 18,
	"spaceLength": 5
}

kingdomDict = {
	"subfolder": "kingdom",
	"height": 24,
	"spaceLength": 7
}

dictionaries = [landmarkDict, cityDict, kingdomDict]

print('# -----START AUTOGENERATED CODE-----')

for d in dictionaries:
	for c in char_range('A', 'Z'):
		im = Image.open('letters/{}/{}.png'.format(d['subfolder'], c))
		print('def letter_{}_{}():\n\treturn ({}, {})\n'.format(d['subfolder'], c, im.width, im.tobytes() + b'\x00\x00\x00\x00'*im.width*(d['height']-im.height)))	

	for c in char_range('a', 'z'):
		im = Image.open('letters/{}/{}.png'.format(d['subfolder'], c))
		print('def letter_{}_{}():\n\treturn ({}, {})\n'.format(d['subfolder'], c, im.width, im.tobytes() + b'\x00\x00\x00\x00'*im.width*(d['height']-im.height)))

	print('def letter_{}_space():\n\treturn ({}, None)\n'.format(d['subfolder'], d['spaceLength']))

	im = Image.open('letters/{}/{}.png'.format(d['subfolder'], 'hyphen'))
	print('def letter_{}_hyphen():\n\treturn ({}, {})\n'.format(d['subfolder'], im.width, im.tobytes() + b'\x00\x00\x00\x00'*im.width*(d['height']-im.height)))

	im = Image.open('letters/{}/{}.png'.format(d['subfolder'], 'apostrophe'))
	print('def letter_{}_apostrophe():\n\treturn ({}, {})\n'.format(d['subfolder'], im.width, im.tobytes() + b'\x00\x00\x00\x00'*im.width*(d['height']-im.height)))

#spaces are 7px in kingdom text
# print(""im.tobytes())

for d in dictionaries:
	print('LETTER_ARR_{} = {{'.format(d['subfolder'].upper()))
	keyVals = []
	for c in char_range('A', 'Z'):
		keyVals.append('\t\'{}\': letter_{}_{}'.format(c, d['subfolder'], c))

	for c in char_range('a', 'z'):
		keyVals.append('\t\'{}\': letter_{}_{}'.format(c, d['subfolder'], c))
	keyVals.append('\t\' \': letter_{}_space'.format(d['subfolder']))
	keyVals.append('\t\'-\': letter_{}_hyphen'.format(d['subfolder']))
	keyVals.append('\t\'\\\'\': letter_{}_apostrophe'.format(d['subfolder']))
	print(',\n'.join(keyVals))
	print('}\n')
print('# -----END AUTOGENERATED CODE-----')